### ISSUE TITLE
support for subscriptions in rego

### ISSUE THREAD

**Issue by chicco785** [orchestracities/opa-authz#11]
**Is your feature request related to a problem? Please describe.**

NGSI apis also include subscriptions, we should test and validate acl also for subscriptions.

**Describe the solution you'd like**

Having a set of rules for subscription resource type.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by Cerfoglg** [comment]
This is actually already supported in the rego rules

**Comment by chicco785** [comment]
indeed: 
[path_matches_policy(resource, resource_type, path) {](https://github.com/orchestracities/opa-authz/blob/1f44bbca914bd1bebbdc6360b3e8b29759560efe/config/opa-service/policy.rego#L99)
https://github.com/orchestracities/opa-authz/blob/1f44bbca914bd1bebbdc6360b3e8b29759560efe/config/opa-service/policy.rego#L108
